using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyConfigurationAttribute("net-4.0.win32")]
[assembly: AssemblyCompanyAttribute("http://www.bugnetproject.com")]
[assembly: AssemblyCopyrightAttribute("Copyright (C) 2008 BugNET Project")]
[assembly: AssemblyProductAttribute("BugNET Open Source Issue Tracker")]
[assembly: AssemblyVersionAttribute("0.8.304")]
[assembly: AssemblyInformationalVersionAttribute("0.8.304")]

